REM   Check the following packages:
REM
REM       PCPM_BATCH_SETTLEMENT_DRIVER
REM       PCPM_SETTLEMENT_SUPPORT
REM


REM set timing on;
REM SHOW PARAMETER OPTIMIZER_MODE


alter session set optimizer_mode = CHOOSE;
--alter session set optimizer_mode = RULE;



DELETE plan_table where statement_id = 'MTI'
/

EXPLAIN PLAN
  SET STATEMENT_ID = 'MTI'
  INTO plan_table
  FOR
SELECT AGGH.KY_CPM_AGG_HEADER, AGGH.TX_AGG_VALUE, M867.KY_PND_SEQ_TRANS, PURPOSE.CD_MAJOR_TYPE, M867.KY_ROW_SEQ_TRANS
      ,M867.QY_QUANTITY, PTH.KY_SUPPLIER, PTH.KY_ENROLL, PTH.KY_BA, PTH.ID_EDC_ACCT_NUM
      ,PTH.DT_PERIOD_START, PTH.DT_PERIOD_END, STATE.CD_SERV_SUPP
      ,STATE.CD_EDC_NM, STATE.TX_STATE, PPH.KY_PROFHDR_SEQ, PPH.CD_WHOBILLS
      ,PPH.FL_IUPREP, PPH.TX_DESCRIPTION, BD.TX_ELEM_VALUE DEAL_TYPE, PTH.DT_BILLED_BY_CSS 
FROM CUSTPRO.CPM_CD_PURPOSE PURPOSE
    ,CUSTPRO.CPM_EDC_STATE STATE
    ,CUSTPRO.CPM_PND_MONTHLY_867 M867
    ,CUSTPRO.CPM_PND_TRAN_HDR PTH
    ,CUSTPRO.CPM_PRODUCT_ACCOUNT PA
    ,CUSTPRO.CPM_PRICE_PROFILE_HDR PPH
    ,CUSTPRO.CPM_PRICE_PROFILE_DTL PPD
    ,CUSTPRO.CPM_BILL_DETERMINANT BD
    ,CUSTPRO.CPM_AGG_HEADER AGGH
    , CUSTPRO.CPM_AGG_MEMBER AGGM 
WHERE :B9 IN (-1, PTH.KY_PND_SEQ_TRANS)    --:B6 IN (-1, PTH.KY_PND_SEQ_TRANS) 
  AND PURPOSE.KY_CPM_CD_PURPOSE = PTH.CD_PURPOSE 
  AND STATE.ID_EDC_DUNS = PTH.ID_EDC_DUNS 
  AND M867.KY_PND_SEQ_TRANS = PTH.KY_PND_SEQ_TRANS 
  AND PTH.KY_ENROLL = PA.KY_ENROLL 
  AND PPH.KY_PROFHDR_SEQ = PA.KY_PROFHDR_SEQ 
  AND PA.KY_PA_SEQ = BD.KY_PA_SEQ 
  AND PA.KY_PROFHDR_SEQ = BD.KY_PROFHDR_SEQ 
  AND PPD.KY_PROFHDR_SEQ = BD.KY_PROFHDR_SEQ 
  AND PPD.KY_PROFDTL_SEQ = BD.KY_PROFDTL_SEQ
  AND PPD.TX_DESCRIPTION = 'SERNA PRODUCT CODE' 
  AND STATE.CD_SERVICE = 'EL' 
  AND STATE.FL_ACTIVE = 'Y' 
  AND M867.CD_REC_TYPE = '03' 
  AND M867.FL_SEND_TO_CSS = 'Y' 
  AND :B5 IN ('-ANY-', PTH.KY_SUPPLIER)
  AND :B4 IN ('-ANY-', STATE.TX_STATE) 
  AND PTH.DT_BILLED_BY_CSS BETWEEN :B3 AND :B2 
  AND PTH.CD_TRAN_STATUS = '75' 
  AND PTH.DT_PERIOD_START BETWEEN PA.DT_EFF_FROM AND PA.DT_EFF_TO 
  AND PPH.CD_PRODUCT_TYPE = 'M' 
  AND PPH.CD_SERVICE = 'EL' 
  AND PPD.CD_EDI_CODE IN ('ENERGY', 'FXONOFFPK%') 
  AND AGGM.KY_ENROLL = PTH.KY_ENROLL 
  AND AGGM.CD_MEMBER_TYPE = 'SUB' 
  AND PTH.DT_PERIOD_START <= AGGM.DT_EFF_TO 
  AND PTH.DT_PERIOD_END >= AGGM.DT_EFF_FROM 
  AND AGGH.KY_CPM_AGG_HEADER = AGGM.KY_CPM_AGG_HEADER 
  AND AGGH.CD_AGG_TYPE = :B1 
ORDER BY PTH.KY_ENROLL, DT_BILLED_BY_CSS, PURPOSE.CD_MAJOR_TYPE DESC, PTH.DT_PERIOD_START, M867.KY_PND_SEQ_TRANS
/

@utlxpls.sql