SELECT  hdr.KY_CALL_LOG_ID
       ,CIS_CL_CALL_TYPES.TX_CALL_TYPE
       ,CIS_CL_LINKED_ACCOUNTS.TX_BILLING_NUMBER, CIS_CL_LINKED_ACCOUNTS.FL_ACTIVE
  FROM CIS_CL_HEADER hdr
      ,CIS_CL_CALL_TYPES
      ,CIS_CL_LINKED_ACCOUNTS
  WHERE CIS_CL_CALL_TYPES.KY_CALL_LOG_ID = hdr.KY_CALL_LOG_ID
    AND CIS_CL_LINKED_ACCOUNTS.KY_CALL_LOG_ID = hdr.KY_CALL_LOG_ID
    --AND hdr.KY_ENROLL = 1566339
    AND hdr.ky_call_log_id = 55006 --120556     54922
/