REM set timing on;
REM SHOW PARAMETER OPTIMIZER_MODE


alter session set optimizer_mode = CHOOSE;
--alter session set optimizer_mode = RULE;



DELETE plan_table where statement_id = 'MTI'
/

EXPLAIN PLAN
  SET STATEMENT_ID = 'MTI'
  INTO plan_table
  FOR
SELECT
                *
             FROM
                (SELECT
                    /*+ FIRST_ROWS(500) */ ACCTS.*,
                    ROWNUM ROW_POSITION
                 FROM
                    (SELECT 
	PPLSCIS.EDI_TRANSACTION.ID_EDI_TRANSACTION, 
	PPLSCIS.EDI_FILE_HEADER.CD_TRANS_DIRECTION, 
	PPLSCIS.EDI_FILE_HEADER.CD_COMM_CHANNEL, 
	PPLSCIS.EDI_FILE_HEADER.CD_EDI_FILE_TYPE, 
	PPLSCIS.EDI_TRANSACTION.TX_UTILITY_NUM, 
	PPLSCIS.EDI_TRANSACTION.TX_OLD_UTILITY_NUM, 
	PPLSCIS.EDI_TRANSACTION.TX_UTILITY_DD4, 
	PPLSCIS.EDI_TRANSACTION.TX_SUPPLIER_NUM, 
	PPLSCIS.EDI_TRANSACTION.TX_SUPPLIER_DD4, 
	PPLSCIS.EDI_TRANSACTION.TX_CUSTOMER_NAME, 
	PPLSCIS.EDI_TRANSACTION.TX_TRANS_REF_NUM, 
	PPLSCIS.EDI_TRANSACTION.TX_XREF_NUM, 
	PPLSCIS.EDI_TRANSACTION.CD_TRANS_TYPE, 
	PPLSCIS.EDI_TRANSACTION.CD_TRANS_SUB_TYPE, 
	PPLSCIS.EDI_TRANSACTION.CD_TRANS_SUB_TYPE_RAW, 
	PPLSCIS.EDI_TRANSACTION.CD_STATE, 
	PPLSCIS.EDI_TRANSACTION.CD_REQ_RESP, 
	PPLSCIS.EDI_TRANSACTION.CD_SERVICE_TYPE, 
	PPLSCIS.EDI_TRANSACTION.CD_PURPOSE_CODE, 
	PPLSCIS.EDI_HEADER.TX_ISA_CONTROL_NUM, 
	PPLSCIS.EDI_FUNC_GROUP.TX_GS_CONTROL_NUM, 
	PPLSCIS.EDI_FUNC_GROUP.DT_GS_DATE, 
	PPLSCIS.EDI_FILE_HEADER.DT_TRANS_DATE, 
	PPLSCIS.EDI_TRANSACTION.DT_MISC_DATE_1, 
	PPLSCIS.EDI_TRANSACTION.DT_DATE_EFFECTIVE_OR_DUE, 
	PPLSCIS.EDI_TRANSACTION.DT_START_DATE, 
	PPLSCIS.EDI_TRANSACTION.DT_END_DATE, 
	PPLSCIS.EDI_TRANSACTION.CD_ACCEPT_REJECT, 
	PPLSCIS.EDI_TRANSACTION.CD_ACTION_CODE, 
	PPLSCIS.EDI_TRANSACTION.TX_UTILITY_NAME, 
	PPLSCIS.EDI_TRANSACTION.TX_SUPPLIER_NAME, 
	PPLSCIS.EDI_TRANSACTION.NO_TRANS_BYTE_START_POS, 
	PPLSCIS.EDI_TRANSACTION.NO_TRANS_BYTE_END_POS, 
	PPLSCIS.EDI_FILE_HEADER.ID_FILENET_DOC_GUID, 
	PPLSCIS.EDI_FILE_HEADER.CD_BUSINESS_UNIT, 
	PPLSCIS.EDI_FILE_HEADER.TX_FILENAME, 
	PPLSCIS.EDI_HEADER.NO_RECORD_DELIMITER_UTF8, 
	PPLSCIS.EDI_REASON.CD_REASON, 
	PPLSCIS.EDI_TRANSACTION.CD_BILL_PRESENTER, 
	PPLSCIS.EDI_TRANSACTION.CD_BILL_CALCULATOR
FROM 
	PPLSCIS.EDI_FILE_HEADER 
	JOIN PPLSCIS.EDI_HEADER ON EDI_HEADER.ID_EDI_FILE_HEADER = PPLSCIS.EDI_FILE_HEADER.ID_EDI_FILE_HEADER 
	JOIN PPLSCIS.EDI_FUNC_GROUP ON EDI_FUNC_GROUP.ID_EDI_HEADER = PPLSCIS.EDI_HEADER.ID_EDI_HEADER 
	JOIN PPLSCIS.EDI_TRANSACTION ON EDI_TRANSACTION.ID_EDI_FUNC_GROUP = PPLSCIS.EDI_FUNC_GROUP.ID_EDI_FUNC_GROUP 
	LEFT JOIN PPLSCIS.EDI_REASON ON EDI_REASON.ID_EDI_TRANSACTION = PPLSCIS.EDI_TRANSACTION.ID_EDI_TRANSACTION
WHERE 
( PPLSCIS.EDI_FILE_HEADER.CD_BUSINESS_UNIT = 'PPLSolutions') AND 	(PPLSCIS.EDI_TRANSACTION.CD_TRANS_TYPE  IN ('810')) AND 
 ( (		 (PPLSCIS.EDI_TRANSACTION.CD_TRANS_SUB_TYPE = 'BR')  
)  )
--ORDER BY PPLSCIS.EDI_TRANSACTION.ID_EDI_TRANSACTION
) ACCTS
                 WHERE
                    ROWNUM <= 500
--                 ORDER BY ID_EDI_TRANSACTION
                 )
             WHERE
                ROW_POSITION > 0
/

@utlxpls.sql