SELECT ID_EDI_FILE_HEADER, CD_BUSINESS_UNIT, CD_TRANS_DIRECTION, CD_COMM_CHANNEL, CD_EDI_FILE_TYPE, ID_FILENET_DOC_GUID, DT_TRANS_DATE 
  FROM EDI_FILE_HEADER 
  WHERE ID_FILENET_DOC_GUID IS NOT NULL 
    AND FL_DOCUMENT_PARSED = 'N' 
    AND DT_TRANS_DATE IS NOT NULL 
    AND TRUNC(DT_TRANS_DATE) >= TRUNC(TO_DATE('01/01/2009','mm/dd/yyyy'))
/

CREATE INDEX mti_edi_file_hdr ON edi_file_header (fl_document_parsed, id_filenet_doc_guid, trunc(dt_trans_date)) TABLESPACE EDI_INDX
/