REM set timing on;
REM SHOW PARAMETER OPTIMIZER_MODE


alter session set optimizer_mode = CHOOSE;
--alter session set optimizer_mode = RULE;



DELETE plan_table where statement_id = 'MTI'
/

EXPLAIN PLAN
  SET STATEMENT_ID = 'MTI'
  INTO plan_table
  FOR
SELECT ACCT.KY_ENROLL, ARREARAGE.TX_BILLING_NUMBER, ACCT.TX_UTILITY_ACCOUNT, ACCT.TX_CUSTOMER_NAME
     , ACCT.TX_DAY_PHONE_AREA || '-' || ACCT.TX_DAY_PHONE "TX_DAY_PHONE", ACCT.KY_UTILITY_NAME
     , ACCT.KY_SERVICE_STATE, NVL(BA.KY_BILLING_STATUS, 'N/A') "KY_BILLING_STATUS", BA.KY_BILL_OPTION
     , BA.KY_CUSTOMER_CARE, ARREARAGE.DT_BILL, ARREARAGE.DT_DUE
     , TO_NUMBER(TRUNC(SYSDATE) - TO_DATE(ARREARAGE.DT_DUE, 'YYYY-MM-DD')) "QY_DAYS_OVERDUE"
     , ARREARAGE.AT_DB "AT_BILL", ARREARAGE.AT_REMN_DB "AT_OVERDUE", ENR.KY_ACCOUNT_MANAGER "KY_ACCOUNT_MANAGER"
     , ENR.KY_SERVICE_LEVEL 
  FROM ( SELECT --+ USE_HASH(B C ACCT_INFO)  
                LPAD(TO_CHAR(ACCT_INFO.KY_BA), 10, '0') TX_BILLING_NUMBER, MIN(ACCT_INFO.DT_BILL) DT_BILL
              , ACCT_INFO.AT_DB AT_DB, SUM(ACCT_INFO.AT_REMN_DB) AT_REMN_DB, ACCT_INFO.KY_SUPPLIER_ID
              , MIN(B.DT_DUE) DT_DUE, C.DT_TARGET_END_CALC, (TO_DATE(MIN(B.DT_DUE), 'YYYY-MM-DD') + :B1 ) PAST_DUE_DATE 
           FROM BILL_INFO_HDR@CL2X B
              , TARGET_CONTRACT@CL2X C
              , ACCT_INFO 
           WHERE ACCT_INFO.KY_BA = B.KY_BA 
             AND ACCT_INFO.DT_BILL = B.DT_BILL 
             AND B.KY_BA = C.KY_BA 
             AND (B.DT_DUE <= TO_CHAR(SYSDATE - :B1 , 'YYYY-MM-DD'))
           GROUP BY ACCT_INFO.KY_SUPPLIER_ID,ACCT_INFO.AT_DB, C.DT_TARGET_END_CALC,ACCT_INFO.KY_BA )  ARREARAGE 
       JOIN BILL_ACCOUNT BA ON BA.TX_BILLING_NUMBER = ARREARAGE.TX_BILLING_NUMBER 
       JOIN ACCOUNT ACCT ON ACCT.KY_ENROLL = BA.KY_ENROLL 
       JOIN ENROLL ENR ON ACCT.KY_ENROLL = ENR.KY_ENROLL 
  WHERE ACCT.KY_ENROLL NOT IN (SELECT KY_ENROLL 
                                 FROM PPLSCIS.CIS_COLLECTIONS_QUEUE_LOG 
                                 WHERE DT_CALL_COMPLETED > TRUNC(SYSDATE) - 5) 
    AND ARREARAGE.AT_REMN_DB >= :B2 
  ORDER BY ACCT.TX_CUSTOMER_NAME, ARREARAGE.DT_BILL
/

@utlxpls.sql