SELECT A.KY_SUPPLIER  SUPPLIER
      ,TO_CHAR(A.KY_ENROLL) ENROLLMENT_NUMBER
      ,TO_CHAR(A.TX_BILLING_NUMBER) BILLING_NUMBER
      ,TO_CHAR(A.TX_UTILITY_ACCOUNT) UTILITY_ACCOUNT
      ,A.TX_CUSTOMER_NAME CUSTOMER_NAME
      ,A.TX_DAY_PHONE PHONE_DAYTIME
      ,A.KY_UTILITY_NAME UTILITY
      ,A.KY_SERVICE_STATE STATE
      ,A.KY_BILLING_STATUS BILLING_STATUS
      ,A.KY_BILL_OPTION BILL_OPTION
      ,A.DT_BILL BILL_DATE
      ,A.DT_DUE DATE_DUE
      ,A.QY_DAYS_OVERDUE DAYS_OVERDUE
      ,A.AT_BILL BILL_AMOUNT
      ,A.AT_OVERDUE AMOUNT_OVERDUE
      ,A.TX_SUMM_BILL_GROUP  SUMMARY_BILL_GROUP
      ,A.KY_ACCOUNT_MANAGER ACCOUNT_MANAGER
      ,(SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI') SERVICE_LEVEL
      --,CASE E.KY_SERVICE_LEVEL
			--						WHEN '5' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						WHEN 'C' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						WHEN 'G' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						WHEN 'L' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						WHEN 'M' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						WHEN 'S' THEN (SELECT TX_DECODE FROM CODE WHERE KY_TABLE ='SERVICE_LEVEL' AND KY_CODE = E.KY_SERVICE_LEVEL AND KY_SUPPLIER = 'TESI')
			--						ELSE E.KY_SERVICE_LEVEL
			 -- END SERVICE_LEVEL
       ,CASE E.FL_KEY_CUSTOMER 
              WHEN  'Y' THEN 'Y' 
              ELSE 'N' 
         END Key_Account
        ,A.DT_LAST_PAYMENT  LAST_PAYMENT_DATE
        ,A.CD_QUEUE_STATUS  QUEUE_STATUS
        ,CASE (A.ID_USER_GUID_HANDLING) 
                WHEN NULL THEN '--'
                ELSE p_cis_collections_reports.GET_USER_ID(A.ID_USER_GUID_HANDLING)
          END id_user_id
        ,CASE 
            WHEN e.ky_service_level NOT IN ('1','2','3','4') THEN '1'
            WHEN e.ky_service_level = '4' THEN '2'
            WHEN e.ky_service_level = '3' THEN '3'
            WHEN e.ky_service_level = '2' THEN '4'
            WHEN e.ky_service_level = '1' THEN '5'
            ELSE '6'
         END sort_order
    FROM CIS_COLLECTIONS_QUEUE A
        ,ENROLL E
    WHERE A.KY_SUPPLIER = E.KY_SUPPLIER
      AND A.KY_ENROLL = E.KY_ENROLL
      AND A.KY_SUPPLIER = 'TESI'
      AND A.CD_QUEUE_STATUS = 'TD'
    ORDER BY sort_order
;