CREATE TEMPORARY TABLESPACE temp2
   TEMPFILE '\oraclexe\app\oracle\oradata\XE\temp2_01.dbf' SIZE 5M REUSE
   AUTOEXTEND ON NEXT 1M MAXSIZE unlimited
   EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
   
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp2;

DROP TABLESPACE temp INCLUDING CONTENTS AND DATAFILES;

CREATE TEMPORARY TABLESPACE temp
  TEMPFILE '\oraclexe\app\oracle\oradata\XE\temp01.dbf' SIZE 500M REUSE
  AUTOEXTEND ON NEXT 100M MAXSIZE unlimited
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
  
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp;

DROP TABLESPACE temp2 INCLUDING CONTENTS AND DATAFILES;