
'EXECDBMS_DDL.ALTER_COMPILE(''PACKAGEBODY'',USER,'''||OBJECT_NAME||''')'                                                                                                                                                                                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                                                                                                       
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'DR_BILL_OPTION')                                                                                                                                                                                                                                         
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'DR_CONTRACTS')                                                                                                                                                                                                                                           
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'GW_CSS_UTIL_FNCTN')                                                                                                                                                                                                                                      
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'GW_TRANSACTION')                                                                                                                                                                                                                                         
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'NCID_P_ACCOUNT_DROP')                                                                                                                                                                                                                                    
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'NCID_P_ACCOUNT_INFO')                                                                                                                                                                                                                                    
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'NCID_P_COMMON')                                                                                                                                                                                                                                          
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'ONE_SIDED_DBCR_INTERFACE')                                                                                                                                                                                                                               
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'REVENUE_ADJUSTMENT_INTERFACE')                                                                                                                                                                                                                           
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'SV_ACCOUNT_EXTRACT')                                                                                                                                                                                                                                     
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'SV_CHANGE_EXTRACT')                                                                                                                                                                                                                                      
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'SV_DECODE_EXTRACT')                                                                                                                                                                                                                                      
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'SV_TRANSACTION_EXTRACT')                                                                                                                                                                                                                                 
EXEC DBMS_DDL.alter_compile('PACKAGE BODY', user, 'SV_TRANSACTION_EXTRACT_PORTAL')                                                                                                                                                                                                                          

14 rows selected.

