REM set timing on;
SHOW PARAMETER OPTIMIZER_MODE
set linesize 300
set pagesize 500


--alter session set optimizer_mode = CHOOSE;
--alter session set optimizer_mode = RULE;

--
--   FOR 11g:
--alter session set optimizer_mode = ALL_ROWS



DELETE plan_table where statement_id = 'MTI';
COMMIT;


EXPLAIN PLAN
  SET STATEMENT_ID = 'MTI'
  INTO plan_table
  FOR
SELECT "EDIADMIN"."EU_EDI_REASON"."CD_REASON" ,"EDIADMIN"."TRANSACTIONS"."ID_EDI_TRANSACTION" ,"EDIADMIN"."TRANSACTIONS"."DT_TRANS_DATE" ,"EDIADMIN"."TRANSACTIONS"."CD_TRANS_DIRECTION" ,"EDIADMIN"."TRANSACTIONS"."TX_UTILITY_NUM" ,"EDIADMIN"."TRANSACTIONS"."TX_OLD_UTILITY_NUM" ,"EDIADMIN"."TRANSACTIONS"."TX_UTILITY_NAME" ,"EDIADMIN"."TRANSACTIONS"."TX_UTILITY_DD4" ,"EDIADMIN"."TRANSACTIONS"."TX_SUPPLIER_NUM" ,"EDIADMIN"."TRANSACTIONS"."TX_SUPPLIER_NAME" ,"EDIADMIN"."TRANSACTIONS"."TX_SUPPLIER_DD4" ,"EDIADMIN"."TRANSACTIONS"."TX_CUSTOMER_NAME" ,"EDIADMIN"."TRANSACTIONS"."TX_TRANS_REF_NUM" ,"EDIADMIN"."TRANSACTIONS"."CD_SERVICE_TYPE" ,"EDIADMIN"."TRANSACTIONS"."TX_XREF_NUM" ,"EDIADMIN"."TRANSACTIONS"."NO_TRANS_BYTE_START_POS" ,"EDIADMIN"."TRANSACTIONS"."NO_TRANS_BYTE_END_POS" ,"EDIADMIN"."TRANSACTIONS"."CD_TRANS_TYPE" ,"EDIADMIN"."TRANSACTIONS"."CD_STATE" ,"EDIADMIN"."TRANSACTIONS"."CD_PURPOSE_CODE" ,"EDIADMIN"."TRANSACTIONS"."CD_BILL_PRESENTER" ,"EDIADMIN"."TRANSACTIONS"."CD_BILL_CALCULATOR" ,"EDIADMIN"."TRANSACTIONS"."DT_DATE_EFFECTIVE_OR_DUE" ,"EDIADMIN"."TRANSACTIONS"."DT_START_DATE" ,"EDIADMIN"."TRANSACTIONS"."DT_END_DATE" ,"EDIADMIN"."TRANSACTIONS"."CD_TRANS_SUB_TYPE" ,"EDIADMIN"."TRANSACTIONS"."DT_MISC_DATE_1" ,"EDIADMIN"."TRANSACTIONS"."TX_MISC_DATE_1_DESCR" ,"EDIADMIN"."TRANSACTIONS"."CD_ACTION_CODE" ,"EDIADMIN"."TRANSACTIONS"."CD_ACCEPT_REJECT" ,"EDIADMIN"."TRANSACTIONS"."CD_TRANS_SUB_TYPE_RAW" ,"EDIADMIN"."TRANSACTIONS"."CD_REQ_RESP" ,"EDIADMIN"."TRANSACTIONS"."TX_SENDER" ,"EDIADMIN"."TRANSACTIONS"."TX_RECEIVER" ,"EDIADMIN"."TRANSACTIONS"."TX_ORIG_REF_NUM" ,"EDIADMIN"."TRANSACTIONS"."INVOICE_AMOUNT" ,"EDIADMIN"."EU_814"."TX_ESP_RATE_CODE" ,"EDIADMIN"."EU_814"."DT_MODIFIED"
FROM "EDIADMIN"."TRANSACTIONS","EDIADMIN"."EU_EDI_REASON", "EDIADMIN"."EU_814"
where ("EDIADMIN"."EU_EDI_REASON"."ID_EDI_TRANSACTION" = "EDIADMIN"."EU_814"."ID_EDI_TRANSACTION"(+) ) 
  and (((((("EDIADMIN"."TRANSACTIONS"."DT_TRANS_DATE" > to_date('2014-07-11 13:15:00','yyyy-mm-dd hh24:mi:ss') ) 
  AND ("EDIADMIN"."TRANSACTIONS"."DT_TRANS_DATE" < to_date('2014-07-18 13:15:59','yyyy-mm-dd hh24:mi:ss') ) ) 
  AND ("EDIADMIN"."TRANSACTIONS"."CD_TRANS_DIRECTION" = 'Inbound' ) ) 
  AND ("EDIADMIN"."TRANSACTIONS"."CD_TRANS_TYPE" = '814' ) ) 
  AND ("EDIADMIN"."EU_EDI_REASON"."ID_EDI_TRANSACTION" = "EDIADMIN"."TRANSACTIONS"."ID_EDI_TRANSACTION" ) ) 
  AND ("EDIADMIN"."EU_EDI_REASON"."CD_REASON" LIKE '%REFRB%' ) )
/


--@utlxpls.sql

--Format Options:
-- 'TYPICAL'. Other values include 'BASIC', 'ALL', 'SERIAL'. There is also an undocumented 'ADVANCED' 
SET HEADING OFF
SELECT * 
  FROM  TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', 'MTI', 'SERIAL'));

SET HEADING ON  

set linesize 100
set pagesize 50